// <auto-generated />
namespace RTLS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class New_Changes_To_Rtls_Configuration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New_Changes_To_Rtls_Configuration));
        
        string IMigrationMetadata.Id
        {
            get { return "201709261413477_New_Changes_To_Rtls_Configuration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
