// <auto-generated />
namespace RTLS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changes_MacAddress_Tbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes_MacAddress_Tbl));
        
        string IMigrationMetadata.Id
        {
            get { return "201707160442216_changes_MacAddress_Tbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
