// <auto-generated />
namespace RTLS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_tbl_MacAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_tbl_MacAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201706270031375_Update_tbl_MacAddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
